FROM golang:1.15.2

RUN go get github.com/githubnemo/CompileDaemon && \
  go get github.com/go-delve/delve/cmd/dlv
WORKDIR /app

COPY .. /app

RUN go mod download


EXPOSE 5000 40000

ENTRYPOINT CompileDaemon --build="go build cmd/auth/main.go" --command="dlv debug --headless --listen=:40000 --api-version=2 --accept-multiclient cmd/auth/main.go"